//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Web.Order {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtid;
		protected global::System.Web.UI.WebControls.TextBox txtorderId;
		protected global::System.Web.UI.WebControls.TextBox txtaddTime;
		protected global::System.Web.UI.WebControls.TextBox txtuserId;
		protected global::System.Web.UI.WebControls.TextBox txtisDel;
		protected global::System.Web.UI.WebControls.TextBox txtwuliuId;
		protected global::System.Web.UI.WebControls.TextBox txtpayId;
		protected global::System.Web.UI.WebControls.TextBox txtisPay;
		protected global::System.Web.UI.WebControls.TextBox txtaddressId;
		protected global::System.Web.UI.WebControls.TextBox txtcouponId;
		protected global::System.Web.UI.WebControls.TextBox txtmemo;
		protected global::System.Web.UI.WebControls.TextBox txttrackingNumber;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
